import numpy as IIIIIIIIIIIIIIIIIIIIIIIIII


def IIIIIIIIIIIIIIIIIIIIIIII(IIIII, IIII):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = IIIII[:IIII]
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = IIIII[IIII + 1 :]
    return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


def IIIIIIIIIIIIIIIIIIIIIIIII(IIII, IIIII):
    return chr((ord(IIII) + ord(IIIII)) // 2)


def IIIIIIIIIIIIIIIIIIIIIIIIIII(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = False
    while (
        len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) != 1107
        and not IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    ):
        if IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII:
            while (
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                ]
                != " "
                and IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                < len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) - 1
            ):
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
            if (
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                < len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) - 1
            ):
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = IIIIIIIIIIIIIIIIIIIIIIII(
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                )
            else:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = False
        else:
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
                len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) - 1
            )
            while (
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                ]
                != " "
                and IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                > IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
            ):
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII -= 1
            if IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII > 0:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = IIIIIIIIIIIIIIIIIIIIIIII(
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                )
            else:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
    return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


def IIIIIIIIIIIIIIIIIIIIIIIIIIII(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
        len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) - 3
    )
    while len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) != 1107:
        if IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII:
            if (
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                < len(IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII) - 2
            ):
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
                    IIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1,
                    )[:IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII]
                    + IIIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                        ],
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1
                        ],
                    )
                    + IIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1,
                    )[IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1 :]
                )
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII += 1
            else:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = False
        else:
            if IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII >= 0:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
                    IIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1,
                    )[:IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII]
                    + IIIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                        ],
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII[
                            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1
                        ],
                    )
                    + IIIIIIIIIIIIIIIIIIIIIIII(
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                        IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1,
                    )[IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII + 1 :]
                )
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII -= 2
            else:
                IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 0
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = True
    return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


def IIIIIIIIIIIIIIIIIIIIIIIIIIIII(x, js):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
        IIIIIIIIIIIIIIIIIIIIIIIIII.random.default_rng()
    )

    if x in js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    elif x in js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][0]
    else:
        return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII.integers(255, size=1)[0]


def IIIIIIIIIIIIIIIIIIIIIIIIIIIIII(x, js):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
        IIIIIIIIIIIIIIIIIIIIIIIIII.random.default_rng()
    )

    if x in js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    elif x in js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][1]
    else:
        return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII.integers(255, size=1)[0]


def IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII(x, js):
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = (
        IIIIIIIIIIIIIIIIIIIIIIIIII.random.default_rng()
    )

    if x in js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["0"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["1"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["2"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["3"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["4"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["5"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["6"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["7"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["8"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["9"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["10"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["11"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["12"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["13"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["14"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    elif x in js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"]:
        return js["15"]["IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII"][2]
    else:
        return IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII.integers(255, size=1)[0]
